name: Check process
on: push

jobs:
    ci-jobs:
        mane: my jobs
        runs-on: ubuntu-latest
        steps:
        - name: run code 
          run: npm install
          env:
            MY_VAR: Hi there! My name is
            FIRST_NAME: Mona
            MIDDLE_NAME: The
            LAST_NAME: Octocat
        - name: show message
            run: |
            echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
          
    